# -*- eval: (git-auto-commit-mode 1) -*-
#+TITLE: Personal importers for the Beancount accounting software

* Introduction
  :PROPERTIES:
  :ID:       872ebd37-febb-4048-820e-896032791585
  :END:
  This repository contains the importers and example configurations I have designed to parse various files and intergrate them in my accounting files for [[http://furius.ca/beancount/][Beancount]].
* Repository struture
  :PROPERTIES:
  :ID:       4e39f2bd-22b8-4dde-ab4f-0134e3743630
  :END:
  - =exemple.import=, the beancount configuration file used to show how to configure the importers in the repository.
  - =importers/smals=, contains all the code related to the processing of data from one of my customer
  - =input=, contains all the files to use to test the importers
* Usage
  :PROPERTIES:
  :ID:       b8d2a7cf-a59f-4859-a5af-b831f05695e2
  :END:
  Beancount must be install with all its dependencies.

  1. Open a terminal on the directory where the code is stored on the disk.
  2. To call the extractor, use the following command:
     #+BEGIN_SRC sh
       bean-extract exemple.import input/smals-report-201812-cleaned.csv
     #+END_SRC
* Description
  :PROPERTIES:
  :ID:       241502ca-b0d5-4581-a3e2-a44cb49a937f
  :END:
** Smals Timesheet Importer package
   :PROPERTIES:
   :ID:       a1e30148-cf0c-47e0-98fc-486e2f0b7f79
   :END:
*** Introduction
    :PROPERTIES:
    :ID:       dd9d908f-98f7-4616-8bee-5413928ca3da
    :END:
The package is meant to be used with the tool provided by the beancount project to create transactions that can be used to record an accounting of my overtime, sickness, vacation and number of worked day in a month.

This package is located in =importers/smals=, it is composed of one file, =__init.py__=.

The main class is =Importer(importer.ImporterProtocol)=, it is respinsible for extracting the data and create the beancount tranactions.
=TimesheetCsvFileDefinition()= is a helper class that is used by the importer to check the file name format in addition to the data format.

*** File format
    :PROPERTIES:
    :ID:       c4e91f8d-a14f-4034-8246-48f1c573834f
    :END:
The input file is a CSV file, using semi-colon (;) as field separator. It contains the time spent at work in addition to sickness, legal holidays and vacation periods.

The fields header must be:
#+BEGIN_EXAMPLE
DATE;DAYTYPE;STD;DAYTYPE2;TIMESPENT;DAYTYPE3;TIMEREC;DAYTYPE4;TIMESPENT2
#+END_EXAMPLE

Field définition:
- DATE: the date of the day in the month
- DAYTYPE: the type of date, may be one of:
  - WK-PT, week-end day
  - minus sign (-), non-worked day other than sickness, vacation or legal Holiday
  - 07:36, the standard working period in day for the customer's employee. This value is simply ignored.
- STD, this field is ignored
- DAYTYPE2, the type of period for half day or the complete day. May be one of:
  - JFR, COLFE, legal holiday
  - MAL, sickness period
  - PRE, worked period
  - CAO, vacation period
- TIMESPENT, the time spent for the period. This value is only used if the value of =DAYTYPE2= is =PRE=
- DAYTYPE3, the type of period for the second half of the day, May be one of:
  - MAL, sickness period
  - PRE, worked period
  - CAO, vacation period
- TIMEREC, the time spent for the period. This value is only used if the value of =DAYTYPE3= is =PRE=
- DAYTYPE4, the type of period for the second half of the day, May be one of:
  - An Empty field
  - CAO, vacation period
- TIMESPENT2, this field is ignored

*** Transaction creation
    :PROPERTIES:
    :ID:       804e5372-1d7b-482c-b7eb-9cb443898094
    :END:

** Utils package
   :PROPERTIES:
   :ID:       2533b708-4245-4e0b-a523-5db1787fff18
   :END:
